import {
  rollMod,
  shuffle,
  modCount,
  SWORD_MODS,
  SHIELD_MODS,
  BOW_MODS,
  AXE_MODS,
  MACE_MODS,
  CROSSBOW_MODS,
  QUIVER_MODS,
  STAFF_MODS,
  SCEPTER_MODS,
  WAND_MODS,
  ARMOR_MODS,
  TOME_MODS,
} from "./modifiers.js";

// ---------------------------------------------------------------------------
// Clases de arma: definen el COMPORTAMIENTO del ataque (lo lee Game.jsx) y en
// qué slot entra el item (lo lee inventoryData.js → kindOf).
//   melee  -> tajo cuerpo a cuerpo
//   ranged -> dispara flechas
//   caster -> dispara bolas / proyectiles de la skill equipada
// ---------------------------------------------------------------------------
export const MELEE_TYPES = new Set(["sword", "axe", "mace"]);
export const RANGED_TYPES = new Set(["bow", "crossbow"]);
export const CASTER_TYPES = new Set(["wand", "staff", "scepter"]);
// Tipos que van en la off hand (weapon2).
export const OFFHAND_TYPES = new Set(["shield", "quiver"]);

export const isMelee = (type) => MELEE_TYPES.has(type);
export const isRanged = (type) => RANGED_TYPES.has(type);
export const isCaster = (type) => CASTER_TYPES.has(type);

// Cada item tiene:
//   - id:   identificador único (define ícono /items/<id>.png y animación de
//           equipo assets/equip/<id>.png con su entrada en EQUIP_ANIMS).
//   - type: categoría de juego (sword / axe / mace / bow / crossbow / quiver /
//           staff / scepter / wand / shield / armor / book_* / jewel). Define en
//           qué slot entra y, para las armas, cómo ataca (ver *_TYPES arriba).
//   - base: atributos base fijos del item (iguales en cada drop). `damage` se
//           enruta a la stat de daño del `tag`; el resto suma a la stat del
//           mismo nombre (attackSpeed, critChance, projectileCount, hp, ...).
//   - tag:  tipo de daño del item (physical/fire/cold/lightning/sacred/demonic).
//   - mods: POOL propio de modificadores posibles (keys de MODIFIERS en
//           modifiers.js). Al dropear, rollItem() toma 1..5 de esta lista y les
//           rollea un valor -> así cada drop del mismo item sale distinto.
//
// Balance por clase (la forma de `base` es lo que distingue a cada clase):
//   sword    daño medio + attackSpeed/critChance
//   axe      daño alto  - attackSpeed, + critDamage
//   mace     daño alto  + defense/hp, - attackSpeed
//   bow      daño medio + attackSpeed
//   crossbow daño alto  + pierceCount, - attackSpeed
//   quiver   (off hand) + projectileCount/attackSpeed, daño elemental plano
//   staff    daño alto  + mp, - attackSpeed
//   scepter  daño medio + mp/critChance
//   wand     daño bajo  + attackSpeed
//   shield   (off hand) defense + blockChance
export const item_list = [
  {
    id: "wand_00",
    type: "wand",
    name: "Duelist Wand",
    version: "neon",
    base: {
      damage: 10,
      requiredLevel: 1,
    },
    mods: [...BOW_MODS],
    tag: "fire",
  },
  {
    id: "sword_10",
    type: "sword",
    name: "Crimson Verdict",
    base: {
      damage: 50,
      requiredLevel: 5,
    },
    mods: [...SWORD_MODS],
    tag: "fire",
  },
  {
    id: "sword_01",
    type: "sword",
    name: "Iron Sword",
    base: {
      damage: 18,
      requiredLevel: 1,
    },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "shield_10",
    type: "shield",
    name: "Tower Shield",
    base: {
      defense: 30,
      blockChance: 25,
      requiredLevel: 2,
    },
    version: "shiny",
    mods: [...SHIELD_MODS],
  },
  {
    id: "jewel_01",
    type: "jewel",
    name: "Void Shard",
    // Material de crafteo: no rollea mods.
    mods: [],
    tag: "misc",
  },
  {
    id: "bow",
    type: "bow",
    name: "Whisperwind",
    base: {
      damage: 35,
      requiredLevel: 6,
    },
    mods: [...BOW_MODS],
    tag: "physical",
  },
  // Skill de proyectil: al equiparla (slot skill) el ataque dispara bolas de
  // fuego, define el daño principal como fuego (por su `tag`) y suma su
  // base.damage (+10) al fireDamage (vía computeStats).
  {
    id: "skill_fireball",
    type: "book_str",
    name: "Fireball",
    description: "Lanza bolas de fuego hacia el cursor.",
    effects: ["+15 to Fire Damage"],
    base: { damage: 15 },
    mods: [],
    tag: "fire",
    // `projectile` marca la skill como ataque a distancia y describe su visual.
    projectile: { color: 0xff7a1a },
    canBeUsedBy: ["empty", "wand", "staff", "scepter"],
  },
  // Skill de proyectil demoníaco: dispara orbes de sombra violetas, define el
  // daño principal como demonic y suma +10 al demonicDamage.
  {
    id: "skill_shadowball",
    type: "book_int",
    name: "Shadow Orb",
    description: "Lanza orbes de sombra demoníaca hacia el cursor.",
    effects: ["+20 to Demonic Damage"],
    base: { damage: 20 },
    mods: [],
    tag: "demonic",
    projectile: { color: 0xa855f7 },
    canBeUsedBy: ["empty", "wand", "staff", "scepter"],
  },
  // Fire arrow
  {
    id: "skill_fireArrow",
    type: "book_dex",
    name: "Fire Arrow",
    description: "Lanza orbes de sombra demoníaca hacia el cursor.",
    effects: ["+20 to Fire Damage"],
    base: { damage: 20 },
    mods: [],
    tag: "fire",
    projectile: { color: 0xff7a1a },
    canBeUsedBy: ["bow", "crossbow"],
  },
  // Lightning arrow
  {
    id: "skill_lightningArrow",
    level: 1,
    type: "book_dex",
    name: "Lightning Arrow",
    description: "Lanza orbes de sombra demoníaca hacia el cursor.",
    effects: [
      "+15 to Lightning Damage",
      "Projectiles pierce 1 additional time",
    ],
    base: { damage: 15, requiredLevel: 5 },
    baseMods: [
      {
        stat: "pierceCount",
        value: "1",
      },
    ],
    mods: [],
    tag: "lightning",
    projectile: { color: 0x7a7aff },
    canBeUsedBy: ["bow", "crossbow"],
  },
  {
    id: "skill_lightningArrow2",
    level: 2,
    type: "book_dex",
    name: "Lightning Arrow",
    description: "Lanza orbes de sombra demoníaca hacia el cursor.",
    effects: [
      "+40 to Lightning Damage",
      "Projectiles pierce 2 additional times",
    ],
    base: { damage: 40, requiredLevel: 25 },
    baseMods: [
      {
        stat: "pierceCount",
        value: "2",
      },
    ],
    mods: [],
    tag: "lightning",
    projectile: { color: 0x7a7aff },
    canBeUsedBy: ["bow", "crossbow"],
  },
  {
    id: "skill_lightningArrow3",
    level: 3,
    type: "book_dex",
    name: "Lightning Arrow",
    description: "Lanza orbes de sombra demoníaca hacia el cursor.",
    effects: [
      "+100 to Lightning Damage",
      "Projectiles pierce 3 additional times",
    ],
    base: { damage: 100, requiredLevel: 40 },
    baseMods: [
      {
        stat: "pierceCount",
        value: "3",
      },
    ],
    mods: [],
    tag: "lightning",
    projectile: { color: 0x7a7aff },
    canBeUsedBy: ["bow", "crossbow"],
  },

  // =========================================================================
  // ESPADAS (main hand, cuerpo a cuerpo). Rápidas y con crítico.
  // =========================================================================
  {
    id: "sword_00",
    type: "sword",
    name: "Duelist Rapier",
    description: "Estoque de esgrima: liviano, preciso y rapidísimo.",
    base: { damage: 14, requiredLevel: 1 },
    // base: { damage: 14, attackSpeed: 14,  requiredLevel: 1 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_02",
    type: "sword",
    name: "Gilded Verdict",
    description: "Hoja dorada con un orbe sagrado engastado en la guarda.",
    base: { damage: 42, requiredLevel: 12 },
    // base: { damage: 42, attackSpeed: 4,  requiredLevel: 12 },
    mods: [...SWORD_MODS],
    tag: "sacred",
  },
  {
    id: "sword_03",
    type: "sword",
    name: "Knight's Longsword",
    description: "Espada larga de acero con guarda de oro.",
    base: { damage: 28, requiredLevel: 6 },
    // base: { damage: 28, attackSpeed: 6, requiredLevel: 6 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_04",
    type: "sword",
    name: "Glacial Fang",
    description: "Colmillo de hielo eterno: corta y congela la herida.",
    base: { damage: 46, requiredLevel: 14 },
    // base: { damage: 46, attackSpeed: 5,  requiredLevel: 14 },
    mods: [...SWORD_MODS],
    tag: "cold",
  },
  {
    id: "sword_05",
    type: "sword",
    name: "Frostburst Edge",
    description: "Al impactar estalla en esquirlas de escarcha.",
    base: { damage: 52, requiredLevel: 18 },
    // base: { damage: 52, attackSpeed: 4,  requiredLevel: 18 },
    mods: [...SWORD_MODS],
    tag: "cold",
  },
  {
    id: "sword_06",
    type: "sword",
    name: "Emberbrand",
    description: "La hoja arde en llamas permanentes.",
    base: { damage: 40, requiredLevel: 12 },
    // base: { damage: 40, attackSpeed: 6, requiredLevel: 12 },
    mods: [...SWORD_MODS],
    tag: "fire",
  },
  {
    id: "sword_07",
    type: "sword",
    name: "Serpent's Coil",
    description: "Hoja serpenteante bañada en veneno demoníaco.",
    base: { damage: 34, requiredLevel: 10 },
    // base: { damage: 34, attackSpeed: 12,  requiredLevel: 10 },
    mods: [...SWORD_MODS],
    tag: "demonic",
  },
  {
    id: "sword_08",
    type: "sword",
    name: "Steel Bastard Sword",
    description: "Espada bastarda de acero templado.",
    base: { damage: 30, requiredLevel: 7 },
    // base: { damage: 30, attackSpeed: 5, requiredLevel: 7 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_09",
    type: "sword",
    name: "Watchman Broadsword",
    description: "Mandoble ancho de la guardia de la ciudad.",
    base: { damage: 33, requiredLevel: 8 },
    // base: { damage: 33, attackSpeed: 4, requiredLevel: 8 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_11",
    type: "sword",
    name: "Legionnaire Gladius",
    description: "Espada corta de legionario: rápida en corto.",
    base: { damage: 20, requiredLevel: 2 },
    // base: { damage: 20, attackSpeed: 10, requiredLevel: 2 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_12",
    type: "sword",
    name: "Lionheart Greatsword",
    description: "Mandoble ceremonial con guarda de león dorado.",
    base: { damage: 58, requiredLevel: 20 },
    // base: { damage: 58, attackSpeed: -6,  requiredLevel: 20 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_13",
    type: "sword",
    name: "Nightbloom Saber",
    description: "Acero violeta que se alimenta de la sombra.",
    base: { damage: 44, requiredLevel: 14 },
    // base: { damage: 44, attackSpeed: 8,  requiredLevel: 14 },
    mods: [...SWORD_MODS],
    tag: "demonic",
  },
  {
    id: "sword_14",
    type: "sword",
    name: "Molten Cleaver",
    description: "Hoja ancha de metal fundido, siempre al rojo vivo.",
    base: { damage: 55, requiredLevel: 19 },
    // base: { damage: 55, attackSpeed: -4,  requiredLevel: 19 },
    mods: [...SWORD_MODS],
    tag: "fire",
  },
  {
    id: "sword_15",
    type: "sword",
    name: "Rimefall Falchion",
    description: "Sable curvo cubierto de escarcha.",
    base: { damage: 38, requiredLevel: 11 },
    // base: { damage: 38, attackSpeed: 9, requiredLevel: 11 },
    mods: [...SWORD_MODS],
    tag: "cold",
  },
  {
    id: "sword_16",
    type: "sword",
    name: "Frostwave Flamberge",
    description: "Hoja ondulada de hielo: cada tajo abre varias heridas.",
    base: { damage: 48, requiredLevel: 16 },
    // base: { damage: 48, attackSpeed: 6,  requiredLevel: 16 },
    mods: [...SWORD_MODS],
    tag: "cold",
  },
  {
    id: "sword_17",
    type: "sword",
    name: "Bronze Warblade",
    description: "Espada de guerra de bronce macizo.",
    base: { damage: 36, requiredLevel: 9 },
    // base: { damage: 36, attackSpeed: 2, requiredLevel: 9 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_18",
    type: "sword",
    name: "Infernal Broadsword",
    description: "Mandoble forjado en la fragua del abismo.",
    base: { damage: 60, requiredLevel: 22 },
    // base: { damage: 60, attackSpeed: -4,  requiredLevel: 22 },
    mods: [...SWORD_MODS],
    tag: "fire",
  },
  {
    id: "sword_19",
    type: "sword",
    name: "Moonsilver Falchion",
    description: "Sable de plata lunar, ligero como el aire.",
    base: { damage: 32, requiredLevel: 8 },
    // base: { damage: 32, attackSpeed: 13,  requiredLevel: 8 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_20",
    type: "sword",
    name: "Ogre's Cleaver",
    description: "Machete gigantesco: lento, brutal, definitivo.",
    base: { damage: 66, requiredLevel: 24 },
    // base: { damage: 66, attackSpeed: -10,  requiredLevel: 24 },
    mods: [...SWORD_MODS],
    tag: "physical",
  },
  {
    id: "sword_21",
    type: "sword",
    name: "Voidshard Blade",
    description: "Esquirlas del vacío ensambladas en una sola hoja.",
    base: { damage: 62, requiredLevel: 23 },
    // base: { damage: 62, attackSpeed: 5,  requiredLevel: 23 },
    mods: [...SWORD_MODS],
    tag: "demonic",
  },
  {
    id: "sword_22",
    type: "sword",
    name: "Clockwork Flail",
    description: "Engranajes cargados que descargan chispas al girar.",
    base: { damage: 45, requiredLevel: 15 },
    // base: { damage: 45, attackSpeed: -2,  requiredLevel: 15 },
    mods: [...SWORD_MODS],
    tag: "lightning",
  },
  {
    id: "sword_23",
    type: "sword",
    name: "Gearwright Keyblade",
    description: "Llave-espada de un artífice: gira y libera una descarga.",
    base: { damage: 50, requiredLevel: 17 },
    // base: { damage: 50, attackSpeed: 3,  requiredLevel: 17 },
    mods: [...SWORD_MODS],
    tag: "lightning",
  },
  {
    id: "sword_24",
    type: "sword",
    name: "Bonecarver Greatsword",
    description: "Mandoble de hueso y hielo dentado.",
    base: { damage: 70, requiredLevel: 26 },
    // base: { damage: 70, attackSpeed: -8,  requiredLevel: 26 },
    mods: [...SWORD_MODS],
    tag: "cold",
  },
  {
    id: "sword_25",
    type: "sword",
    name: "Arclight Saber",
    description: "Hoja de energía pura contenida en un mango de acero.",
    base: { damage: 54, requiredLevel: 20 },
    // base: { damage: 54, attackSpeed: 18,  requiredLevel: 20 },
    mods: [...SWORD_MODS],
    tag: "lightning",
  },

  // =========================================================================
  // HACHAS (main hand, cuerpo a cuerpo). Lentas, mucho daño y crítico brutal.
  // =========================================================================
  {
    id: "axe_00",
    type: "axe",
    name: "Woodsman Hatchet",
    description: "Hacha de leñador. Sirve para talar y para pelear.",
    base: { damage: 22, requiredLevel: 2 },
    // base: { damage: 22, attackSpeed: -2,  requiredLevel: 2 },
    mods: [...AXE_MODS],
    tag: "physical",
  },
  {
    id: "axe_01",
    type: "axe",
    name: "Bronze Double Axe",
    description: "Hacha doble de bronce con filos gemelos.",
    base: { damage: 34, requiredLevel: 8 },
    // base: { damage: 34, attackSpeed: -4,  requiredLevel: 8 },
    mods: [...AXE_MODS],
    tag: "physical",
  },
  {
    id: "axe_02",
    type: "axe",
    name: "Frostbite Axe",
    description: "El filo está sellado en hielo perpetuo.",
    base: { damage: 42, requiredLevel: 13 },
    // base: { damage: 42, attackSpeed: -4,  requiredLevel: 13 },
    mods: [...AXE_MODS],
    tag: "cold",
  },
  {
    id: "axe_03",
    type: "axe",
    name: "Glacier Splitter",
    description: "Hacha doble de la que gotea hielo derretido.",
    base: { damage: 56, requiredLevel: 20 },
    // base: { damage: 56, attackSpeed: -7,  requiredLevel: 20 },
    mods: [...AXE_MODS],
    tag: "cold",
  },
  {
    id: "axe_04",
    type: "axe",
    name: "Crowned Warcleaver",
    description: "Hacha coronada de una orden sagrada.",
    base: { damage: 46, requiredLevel: 15 },
    // base: { damage: 46, attackSpeed: -3,  requiredLevel: 15 },
    mods: [...AXE_MODS],
    tag: "sacred",
  },
  {
    id: "axe_05",
    type: "axe",
    name: "Cinderclaw Axe",
    description: "Los dos filos arden como garras de brasa.",
    base: { damage: 48, requiredLevel: 16 },
    // base: { damage: 48, attackSpeed: -3,  requiredLevel: 16 },
    mods: [...AXE_MODS],
    tag: "fire",
  },
  {
    id: "axe_06",
    type: "axe",
    name: "Magmareaver",
    description: "Hacha de magma solidificado, todavía humeante.",
    base: { damage: 64, requiredLevel: 24 },
    // base: { damage: 64, attackSpeed: -8,  requiredLevel: 24 },
    mods: [...AXE_MODS],
    tag: "fire",
  },
  {
    id: "axe_07",
    type: "axe",
    name: "Sapphire Sovereign Axe",
    description: "Oro y zafiros: el hacha de un rey coronado.",
    base: { damage: 52, requiredLevel: 18 },
    // base: { damage: 52, attackSpeed: -4,  requiredLevel: 18 },
    mods: [...AXE_MODS],
    tag: "sacred",
  },
  {
    id: "axe_08",
    type: "axe",
    name: "Bloodrite Axe",
    description: "Usada en ritos de sangre; nunca termina de secarse.",
    base: { damage: 58, requiredLevel: 21 },
    // base: { damage: 58, attackSpeed: -5,  requiredLevel: 21 },
    mods: [...AXE_MODS],
    tag: "demonic",
  },
  {
    id: "axe_09",
    type: "axe",
    name: "Duskbite Hatchet",
    description: "Hacha corta teñida de penumbra.",
    base: { damage: 30, requiredLevel: 7 },
    // base: { damage: 30, attackSpeed: 0,  requiredLevel: 7 },
    mods: [...AXE_MODS],
    tag: "demonic",
  },
  {
    id: "axe_10",
    type: "axe",
    name: "Dawnbreaker Axe",
    description: "Hacha doble de oro radiante: parte la noche en dos.",
    base: { damage: 68, requiredLevel: 26 },
    // base: { damage: 68, attackSpeed: -6,  requiredLevel: 26 },
    mods: [...AXE_MODS],
    tag: "sacred",
  },

  // =========================================================================
  // MAZAS Y MARTILLOS (main hand, cuerpo a cuerpo). Pesadas: daño + defensa.
  // =========================================================================
  {
    id: "mace_00",
    type: "mace",
    name: "Crimson Morningstar",
    description: "Lucero del alba con púas de cristal carmesí.",
    base: { damage: 38, requiredLevel: 11 },
    // base: { damage: 38, attackSpeed: -4,  requiredLevel: 11 },
    mods: [...MACE_MODS],
    tag: "demonic",
  },
  {
    id: "mace_01",
    type: "mace",
    name: "Copper Warhammer",
    description: "Martillo de guerra de cobre remachado.",
    base: { damage: 26, requiredLevel: 4 },
    // base: { damage: 26, attackSpeed: -3,  requiredLevel: 4 },
    mods: [...MACE_MODS],
    tag: "physical",
  },
  {
    id: "mace_02",
    type: "mace",
    name: "Templar Warhammer",
    description: "Martillo de templario, bendecido antes de cada batalla.",
    base: { damage: 50, requiredLevel: 17 },
    // base: { damage: 50, attackSpeed: -5,  requiredLevel: 17 },
    mods: [...MACE_MODS],
    tag: "sacred",
  },
  {
    id: "mace_03",
    type: "mace",
    name: "Voidstar Morningstar",
    description: "Estrella de vacío que absorbe la luz alrededor.",
    base: { damage: 54, requiredLevel: 19 },
    // base: { damage: 54, attackSpeed: -4,  requiredLevel: 19 },
    mods: [...MACE_MODS],
    tag: "demonic",
  },
  {
    id: "mace_04",
    type: "mace",
    name: "Ironclad Sledge",
    description: "Mazo de acero y oro. Rompe escudos y huesos.",
    base: { damage: 60, requiredLevel: 22 },
    // base: { damage: 60, attackSpeed: -8,  requiredLevel: 22 },
    mods: [...MACE_MODS],
    tag: "physical",
  },
  {
    id: "mace_05",
    type: "mace",
    name: "Ruinlight Mace",
    description: "Oro profanado con gemas de amatista corrupta.",
    base: { damage: 46, requiredLevel: 15 },
    // base: { damage: 46, attackSpeed: -4,  requiredLevel: 15 },
    mods: [...MACE_MODS],
    tag: "demonic",
  },
  {
    id: "mace_06",
    type: "mace",
    name: "Serpentine Gold Mace",
    description: "Maza dorada con serpientes talladas en la cabeza.",
    base: { damage: 42, requiredLevel: 13 },
    // base: { damage: 42, attackSpeed: -2,  requiredLevel: 13 },
    mods: [...MACE_MODS],
    tag: "sacred",
  },
  {
    id: "mace_07",
    type: "mace",
    name: "Starfall Mace",
    description: "Coronada por una estrella de plata caída del cielo.",
    base: { damage: 44, requiredLevel: 14 },
    // base: { damage: 44, attackSpeed: -3,  requiredLevel: 14 },
    mods: [...MACE_MODS],
    tag: "sacred",
  },
  {
    id: "mace_08",
    type: "mace",
    name: "Sapphire Bulwark Mace",
    description: "Maza-baluarte con un zafiro que irradia frío.",
    base: { damage: 40, requiredLevel: 12 },
    // base: { damage: 40, attackSpeed: -3,  requiredLevel: 12 },
    mods: [...MACE_MODS],
    tag: "cold",
  },
  {
    id: "mace_09",
    type: "mace",
    name: "Ashfall Maul",
    description: "Mazo de ceniza y brasa que deja rastros de fuego.",
    base: { damage: 62, requiredLevel: 23 },
    // base: { damage: 62, attackSpeed: -7,  requiredLevel: 23 },
    mods: [...MACE_MODS],
    tag: "fire",
  },

  // =========================================================================
  // ARCOS (main hand, a distancia: disparan flechas).
  // =========================================================================
  {
    id: "bow_00",
    type: "bow",
    name: "Hunter's Shortbow",
    description: "Arco corto de caza, de madera curada.",
    base: { damage: 20, requiredLevel: 1 },
    // base: { damage: 20, attackSpeed: 8, requiredLevel: 1 },
    mods: [...BOW_MODS],
    tag: "physical",
  },
  {
    id: "bow_01",
    type: "bow",
    name: "Emberstring Bow",
    description: "La cuerda incendia cada flecha al tensarse.",
    base: { damage: 38, requiredLevel: 12 },
    // base: { damage: 38, attackSpeed: 8, requiredLevel: 12 },
    mods: [...BOW_MODS],
    tag: "fire",
  },
  {
    id: "bow_02",
    type: "bow",
    name: "Frostspine Bow",
    description: "Arco de espinas de hielo: las flechas salen congeladas.",
    base: { damage: 44, pierceCount: 1, requiredLevel: 15 },
    // base: { damage: 44, attackSpeed: 6, pierceCount: 1, requiredLevel: 15 },
    mods: [...BOW_MODS],
    tag: "cold",
  },
  {
    id: "bow_03",
    type: "bow",
    name: "Glacial Recurve",
    description: "Arco recurvo tallado en un solo bloque de hielo.",
    base: { damage: 34, requiredLevel: 10 },
    // base: { damage: 34, attackSpeed: 9, requiredLevel: 10 },
    mods: [...BOW_MODS],
    tag: "cold",
  },
  {
    id: "bow_04",
    type: "bow",
    name: "Pale Gemwood Bow",
    description: "Madera pálida con gemas engastadas en los brazos.",
    base: { damage: 30, requiredLevel: 8 },
    // base: { damage: 30, attackSpeed: 10,  requiredLevel: 8 },
    mods: [...BOW_MODS],
    tag: "physical",
  },
  {
    id: "bow_05",
    type: "bow",
    name: "Dawnlight Longbow",
    description: "Arco largo que brilla con luz del amanecer.",
    base: { damage: 52, projectileCount: 1, requiredLevel: 20 },
    // base: { damage: 52, attackSpeed: 7, projectileCount: 1, requiredLevel: 20 },
    mods: [...BOW_MODS],
    tag: "sacred",
  },
  {
    id: "bow_06",
    type: "bow",
    name: "Bloodthorn Bow",
    description: "Arco de espinas que se cobra sangre al tensarse.",
    base: { damage: 40, requiredLevel: 13 },
    // base: { damage: 40, attackSpeed: 8,  requiredLevel: 13 },
    mods: [...BOW_MODS],
    tag: "demonic",
  },
  {
    id: "bow_07",
    type: "bow",
    name: "Bonecrest Bow",
    description: "Hueso pálido con una cresta que sangra penumbra.",
    base: { damage: 46, pierceCount: 1, requiredLevel: 16 },
    // base: { damage: 46, attackSpeed: 7, pierceCount: 1, requiredLevel: 16 },
    mods: [...BOW_MODS],
    tag: "demonic",
  },
  {
    id: "bow_08",
    type: "bow",
    name: "Gilded Recurve Bow",
    description: "Arco recurvo con apliques de oro y hueso.",
    base: { damage: 36, requiredLevel: 11 },
    // base: { damage: 36, attackSpeed: 9, requiredLevel: 11 },
    mods: [...BOW_MODS],
    tag: "physical",
  },
  {
    id: "bow_09",
    type: "bow",
    name: "Stormweave Bow",
    description: "Cuerdas entrelazadas que chispean con cada disparo.",
    base: {
      damage: 48,

      // attackSpeed: 12,
      projectileCount: 1,
      requiredLevel: 18,
    },
    mods: [...BOW_MODS],
    tag: "lightning",
  },
  {
    id: "bow_10",
    type: "bow",
    name: "Verdant Shortbow",
    description: "Arco corto de madera verde, apenas curado.",
    base: { damage: 18, requiredLevel: 1 },
    // base: { damage: 18, attackSpeed: 10, requiredLevel: 1 },
    mods: [...BOW_MODS],
    tag: "physical",
  },

  // =========================================================================
  // BALLESTAS (main hand, a distancia). Más lentas y pesadas que los arcos,
  // pero perforan.
  // =========================================================================
  {
    id: "crossbow_00",
    type: "crossbow",
    name: "Oak Crossbow",
    description: "Ballesta de roble, sencilla y confiable.",
    base: { damage: 28, pierceCount: 1, requiredLevel: 3 },
    // base: { damage: 28, attackSpeed: -4, pierceCount: 1, requiredLevel: 3 },
    mods: [...CROSSBOW_MODS],
    tag: "physical",
  },
  {
    id: "crossbow_01",
    type: "crossbow",
    name: "Emberbolt Crossbow",
    description: "Los virotes se encienden al salir del riel.",
    base: { damage: 42, pierceCount: 1, requiredLevel: 13 },
    // base: { damage: 42, attackSpeed: -4, pierceCount: 1, requiredLevel: 13 },
    mods: [...CROSSBOW_MODS],
    tag: "fire",
  },
  {
    id: "crossbow_02",
    type: "crossbow",
    name: "Magmabolt Crossbow",
    description: "Cuerpo de roca fundida que dispara escoria ardiente.",
    base: { damage: 56, pierceCount: 2, requiredLevel: 20 },
    // base: { damage: 56, attackSpeed: -6, pierceCount: 2, requiredLevel: 20 },
    mods: [...CROSSBOW_MODS],
    tag: "fire",
  },
  {
    id: "crossbow_03",
    type: "crossbow",
    name: "Frostbolt Crossbow",
    description: "Ballesta de hielo macizo: los virotes salen escarchados.",
    base: { damage: 46, pierceCount: 2, requiredLevel: 15 },
    // base: { damage: 46, attackSpeed: -4, pierceCount: 2, requiredLevel: 15 },
    mods: [...CROSSBOW_MODS],
    tag: "cold",
  },
  {
    id: "crossbow_04",
    type: "crossbow",
    name: "Duskgold Arbalest",
    description: "Arbalesta de oro con incrustaciones de amatista oscura.",
    base: { damage: 50, pierceCount: 1, requiredLevel: 17 },
    // base: { damage: 50, attackSpeed: -3, pierceCount: 1, requiredLevel: 17 },
    mods: [...CROSSBOW_MODS],
    tag: "demonic",
  },
  {
    id: "crossbow_05",
    type: "crossbow",
    name: "Stormgold Arbalest",
    description: "El riel acumula carga entre disparo y disparo.",
    base: { damage: 54, pierceCount: 2, requiredLevel: 19 },
    // base: { damage: 54, attackSpeed: -2, pierceCount: 2, requiredLevel: 19 },
    mods: [...CROSSBOW_MODS],
    tag: "lightning",
  },
  {
    id: "crossbow_06",
    type: "crossbow",
    name: "Bloodbloom Crossbow",
    description: "Florece en carmesí cada vez que cobra una vida.",
    base: { damage: 44, requiredLevel: 14 },
    // base: { damage: 44, attackSpeed: -3,  requiredLevel: 14 },
    mods: [...CROSSBOW_MODS],
    tag: "demonic",
  },
  {
    id: "crossbow_07",
    type: "crossbow",
    name: "Nightveil Crossbow",
    description: "Ballesta envuelta en un velo de sombra.",
    base: { damage: 38, pierceCount: 1, requiredLevel: 11 },
    // base: { damage: 38, attackSpeed: -2, pierceCount: 1, requiredLevel: 11 },
    mods: [...CROSSBOW_MODS],
    tag: "demonic",
  },
  {
    id: "crossbow_08",
    type: "crossbow",
    name: "Sunforged Arbalest",
    description: "Forjada al sol del mediodía por una orden sagrada.",
    base: { damage: 60, pierceCount: 2, requiredLevel: 22 },
    // base: { damage: 60, attackSpeed: -4, pierceCount: 2, requiredLevel: 22 },
    mods: [...CROSSBOW_MODS],
    tag: "sacred",
  },
  {
    id: "crossbow_09",
    type: "crossbow",
    name: "Bronze Sapphire Crossbow",
    description: "Bronce macizo con un zafiro en el gatillo.",
    base: { damage: 34, pierceCount: 1, requiredLevel: 9 },
    // base: { damage: 34, attackSpeed: -3, pierceCount: 1, requiredLevel: 9 },
    mods: [...CROSSBOW_MODS],
    tag: "physical",
  },

  // =========================================================================
  // CARCAJES (off hand, para arquería). No dan defensa: dan proyectiles,
  // velocidad y daño elemental plano en las flechas.
  // =========================================================================
  {
    id: "quiver_00",
    type: "quiver",
    name: "Leather Quiver",
    description: "Carcaj de cuero simple. Aguanta unas cuantas flechas.",
    base: { requiredLevel: 1 },
    // base: { attackSpeed: 5, requiredLevel: 1 },
    mods: [...QUIVER_MODS],
    tag: "physical",
  },
  {
    id: "quiver_01",
    type: "quiver",
    name: "Ranger's Quiver",
    description: "Carcaj de explorador con bandolera reforzada.",
    base: { damage: 6, projectileCount: 1, requiredLevel: 4 },
    // base: { damage: 6, attackSpeed: 6, projectileCount: 1, requiredLevel: 4 },
    mods: [...QUIVER_MODS],
    tag: "physical",
  },
  {
    id: "quiver_02",
    type: "quiver",
    name: "Frostwind Quiver",
    description: "Las flechas guardadas acá salen cubiertas de escarcha.",
    base: { damage: 12, requiredLevel: 12 },
    // base: { damage: 12, attackSpeed: 5, requiredLevel: 12 },
    mods: [...QUIVER_MODS],
    tag: "cold",
  },
  {
    id: "quiver_03",
    type: "quiver",
    name: "Ember Quiver",
    description: "Cuero curtido al fuego: las puntas ya vienen encendidas.",
    base: { damage: 10, requiredLevel: 10 },
    // base: { damage: 10, attackSpeed: 5, requiredLevel: 10 },
    mods: [...QUIVER_MODS],
    tag: "fire",
  },
  {
    id: "quiver_04",
    type: "quiver",
    name: "Blazing Quiver",
    description: "Arde sin consumirse. Las flechas también.",
    base: { damage: 18, pierceCount: 1, requiredLevel: 18 },
    // base: { damage: 18, attackSpeed: 6, pierceCount: 1, requiredLevel: 18 },
    mods: [...QUIVER_MODS],
    tag: "fire",
  },
  {
    id: "quiver_05",
    type: "quiver",
    name: "Glacial Quiver",
    description: "Carcaj tallado en hielo azul compacto.",
    base: { damage: 16, pierceCount: 1, requiredLevel: 16 },
    // base: { damage: 16, attackSpeed: 5, pierceCount: 1, requiredLevel: 16 },
    mods: [...QUIVER_MODS],
    tag: "cold",
  },
  {
    id: "quiver_06",
    type: "quiver",
    name: "Sunlit Reliquary",
    description: "Relicario dorado que consagra cada flecha antes de volar.",
    base: {
      damage: 22,

      // attackSpeed: 7,
      projectileCount: 1,
      requiredLevel: 22,
    },
    mods: [...QUIVER_MODS],
    tag: "sacred",
  },
  {
    id: "quiver_07",
    type: "quiver",
    name: "Nightshade Quiver",
    description: "Cuero teñido con savia de belladona.",
    base: { damage: 14, requiredLevel: 14 },
    // base: { damage: 14, attackSpeed: 6,  requiredLevel: 14 },
    mods: [...QUIVER_MODS],
    tag: "demonic",
  },
  {
    id: "quiver_08",
    type: "quiver",
    name: "Bloodfeather Quiver",
    description: "Las plumas de las flechas están empapadas en sangre.",
    base: { damage: 20, requiredLevel: 20 },
    // base: { damage: 20, attackSpeed: 6,  requiredLevel: 20 },
    mods: [...QUIVER_MODS],
    tag: "demonic",
  },
  {
    id: "quiver_09",
    type: "quiver",
    name: "Gilded Slim Quiver",
    description:
      "Carcaj angosto y dorado: liviano, se saca la flecha al toque.",
    base: { damage: 8, requiredLevel: 8 },
    // base: { damage: 8, attackSpeed: 12, requiredLevel: 8 },
    mods: [...QUIVER_MODS],
    tag: "sacred",
  },
  {
    id: "quiver_10",
    type: "quiver",
    name: "Sunwrought Quiver",
    description: "Oro labrado por herreros de la aurora.",
    base: {
      damage: 24,

      // attackSpeed: 8,
      projectileCount: 1,
      pierceCount: 1,
      requiredLevel: 24,
    },
    mods: [...QUIVER_MODS],
    tag: "sacred",
  },

  // =========================================================================
  // BASTONES (main hand, casteo: disparan proyectiles). Mucho daño y maná,
  // pero lentos.
  // =========================================================================
  {
    id: "staff_00",
    type: "staff",
    name: "Frostcrown Staff",
    description: "Corona de cristales de hielo sobre un asta rúnica.",
    base: { damage: 40, requiredLevel: 12 },
    // base: { damage: 40, attackSpeed: -2,  requiredLevel: 12 },
    mods: [...STAFF_MODS],
    tag: "cold",
  },
  {
    id: "staff_01",
    type: "staff",
    name: "Voidgate Staff",
    description: "El aro del tope es una puerta al vacío.",
    base: { damage: 56, requiredLevel: 20 },
    // base: { damage: 56, attackSpeed: -4,  requiredLevel: 20 },
    mods: [...STAFF_MODS],
    tag: "demonic",
  },
  {
    id: "staff_02",
    type: "staff",
    name: "Sunspire Staff",
    description: "Bastón dorado con un sol de púas en la punta.",
    base: { damage: 44, requiredLevel: 14 },
    // base: { damage: 44, attackSpeed: -2,  requiredLevel: 14 },
    mods: [...STAFF_MODS],
    tag: "sacred",
  },
  {
    id: "staff_03",
    type: "staff",
    name: "Solar Orb Staff",
    description: "Un orbe radiante suspendido en un anillo de oro.",
    base: {
      damage: 60,

      // attackSpeed: -3,

      projectileCount: 1,
      requiredLevel: 22,
    },
    mods: [...STAFF_MODS],
    tag: "sacred",
  },
  {
    id: "staff_04",
    type: "staff",
    name: "Bloodmoon Staff",
    description: "Cristales carmesí que palpitan como un corazón.",
    base: { damage: 48, requiredLevel: 16 },
    // base: { damage: 48, attackSpeed: -2,  requiredLevel: 16 },
    mods: [...STAFF_MODS],
    tag: "demonic",
  },
  {
    id: "staff_05",
    type: "staff",
    name: "Astral Loop Staff",
    description: "Anillos de oro que orbitan una esfera cargada.",
    base: { damage: 52, requiredLevel: 18 },
    // base: { damage: 52, attackSpeed: 2,  requiredLevel: 18 },
    mods: [...STAFF_MODS],
    tag: "lightning",
  },
  {
    id: "staff_06",
    type: "staff",
    name: "Deepwater Orb Staff",
    description: "Un orbe azul profundo, frío al tacto.",
    base: { damage: 34, requiredLevel: 10 },
    // base: { damage: 34, attackSpeed: -2,  requiredLevel: 10 },
    mods: [...STAFF_MODS],
    tag: "cold",
  },
  {
    id: "staff_07",
    type: "staff",
    name: "Pyreheart Staff",
    description: "La cabeza es una hoguera que nunca se apaga.",
    base: { damage: 50, requiredLevel: 17 },
    // base: { damage: 50, attackSpeed: -2,  requiredLevel: 17 },
    mods: [...STAFF_MODS],
    tag: "fire",
  },
  {
    id: "staff_08",
    type: "staff",
    name: "Amethyst Eye Staff",
    description: "Un ojo de amatista que parpadea cuando nadie mira.",
    base: { damage: 38, requiredLevel: 11 },
    // base: { damage: 38, attackSpeed: -1,  requiredLevel: 11 },
    mods: [...STAFF_MODS],
    tag: "demonic",
  },
  {
    id: "staff_09",
    type: "staff",
    name: "Frostgale Staff",
    description: "Estrella de escarcha que levanta viento helado.",
    base: {
      damage: 46,

      // attackSpeed: -2,

      projectileCount: 1,
      requiredLevel: 15,
    },
    mods: [...STAFF_MODS],
    tag: "cold",
  },
  {
    id: "staff_10",
    type: "staff",
    name: "Skullbinder Staff",
    description: "Un cráneo atado al asta con alambre de plata.",
    base: { damage: 30, requiredLevel: 7 },
    // base: { damage: 30, attackSpeed: -1,  requiredLevel: 7 },
    mods: [...STAFF_MODS],
    tag: "demonic",
  },
  {
    id: "staff_11",
    type: "staff",
    name: "Aetherglow Staff",
    description: "Oro y gemas de éter que zumban con energía contenida.",
    base: { damage: 42, requiredLevel: 13 },
    // base: { damage: 42, attackSpeed: 1,  requiredLevel: 13 },
    mods: [...STAFF_MODS],
    tag: "lightning",
  },

  // =========================================================================
  // CETROS (main hand, casteo de una mano). Menos daño que un bastón, más
  // crítico y maná.
  // =========================================================================
  {
    id: "scepter_00",
    type: "scepter",
    name: "Shardbloom Scepter",
    description: "Cristales de hielo que florecen alrededor de la cabeza.",
    base: { damage: 38, requiredLevel: 12 },
    mods: [...SCEPTER_MODS],
    tag: "cold",
  },
  {
    id: "scepter_01",
    type: "scepter",
    name: "Eclipse Scepter",
    description: "Un anillo de luz violeta rodeando un agujero de nada.",
    base: { damage: 58, requiredLevel: 21 },
    mods: [...SCEPTER_MODS],
    tag: "demonic",
  },
  {
    id: "scepter_02",
    type: "scepter",
    name: "Sapphire Shard Scepter",
    description: "Una esquirla de zafiro sujeta por garras de bronce.",
    base: { damage: 34, requiredLevel: 10 },
    mods: [...SCEPTER_MODS],
    tag: "cold",
  },
  {
    id: "scepter_03",
    type: "scepter",
    name: "Clockwork Sigil Scepter",
    description: "Un engranaje-sello que gira solo y suelta chispas.",
    base: { damage: 40, requiredLevel: 13 },
    mods: [...SCEPTER_MODS],
    tag: "lightning",
  },
  {
    id: "scepter_04",
    type: "scepter",
    name: "Crescent Nebula Scepter",
    description: "Una luna dorada abrazando una nebulosa violeta.",
    base: { damage: 46, requiredLevel: 16 },
    mods: [...SCEPTER_MODS],
    tag: "demonic",
  },
  {
    id: "scepter_05",
    type: "scepter",
    name: "Orrery Scepter",
    description: "Un pequeño planetario que predice la tormenta.",
    base: { damage: 44, requiredLevel: 15 },
    mods: [...SCEPTER_MODS],
    tag: "lightning",
  },
  {
    id: "scepter_06",
    type: "scepter",
    name: "Amethyst Prism Scepter",
    description: "Prisma de amatista montado en un asta de hierro.",
    base: { damage: 30, requiredLevel: 8 },
    mods: [...SCEPTER_MODS],
    tag: "demonic",
  },

  // =========================================================================
  // VARITAS (main hand, casteo rápido). Poco daño, mucha velocidad.
  // =========================================================================
  {
    id: "wand_01",
    type: "wand",
    name: "Ossuary Wand",
    description: "Varita de hueso con un cráneo enjaulado en plata.",
    base: { damage: 24, requiredLevel: 5 },
    // base: { damage: 24, attackSpeed: 12,  requiredLevel: 5 },
    mods: [...WAND_MODS],
    tag: "demonic",
  },
  {
    id: "wand_02",
    type: "wand",
    name: "Skullbone Wand",
    description: "Un fémur y un cráneo chico. Barata pero efectiva.",
    base: { damage: 20, requiredLevel: 3 },
    // base: { damage: 20, attackSpeed: 14,  requiredLevel: 3 },
    mods: [...WAND_MODS],
    tag: "demonic",
  },
  {
    id: "wand_03",
    type: "wand",
    name: "Emberloop Wand",
    description: "Un aro de fuego girando en la punta.",
    base: { damage: 32, requiredLevel: 9 },
    // base: { damage: 32, attackSpeed: 12,  requiredLevel: 9 },
    mods: [...WAND_MODS],
    tag: "fire",
  },
  {
    id: "wand_04",
    type: "wand",
    name: "Frostspark Wand",
    description: "Cristales de hielo que chasquean al castear.",
    base: { damage: 30, requiredLevel: 8 },
    // base: { damage: 30, attackSpeed: 13,  requiredLevel: 8 },
    mods: [...WAND_MODS],
    tag: "cold",
  },
  {
    id: "wand_05",
    type: "wand",
    name: "Bloodthorn Wand",
    description: "Espinas carmesí que se cierran sobre la mano.",
    base: {
      damage: 36,

      // attackSpeed: 11,

      requiredLevel: 11,
    },
    mods: [...WAND_MODS],
    tag: "demonic",
  },
  {
    id: "wand_06",
    type: "wand",
    name: "Sunburst Wand",
    description: "Un estallido de oro que no se apaga nunca.",
    base: { damage: 34, requiredLevel: 10 },
    // base: { damage: 34, attackSpeed: 12,  requiredLevel: 10 },
    mods: [...WAND_MODS],
    tag: "sacred",
  },

  // =========================================================================
  // ESCUDOS (off hand). Defensa + bloqueo; el `tag` es su afinidad elemental.
  // =========================================================================
  {
    id: "shield_00",
    type: "shield",
    name: "Wooden Round Shield",
    description: "Tablas de roble con refuerzos de hierro.",
    base: { defense: 12, blockChance: 12, requiredLevel: 1 },
    mods: [...SHIELD_MODS],
    tag: "physical",
  },
  {
    id: "shield_01",
    type: "shield",
    name: "Emberguard Kite Shield",
    description: "Escudo de cometa con el sello del fuego.",
    base: { defense: 40, blockChance: 20, requiredLevel: 12 },
    mods: [...SHIELD_MODS],
    tag: "fire",
  },
  {
    id: "shield_02",
    type: "shield",
    name: "Frostwolf Shield",
    description: "Un lobo de hielo grabado en la placa.",
    base: { defense: 46, blockChance: 22, requiredLevel: 14 },
    mods: [...SHIELD_MODS],
    tag: "cold",
  },
  {
    id: "shield_03",
    type: "shield",
    name: "Flameheart Round Shield",
    description: "Rodela con un corazón de fuego en el centro.",
    base: { defense: 38, blockChance: 18, requiredLevel: 11 },
    mods: [...SHIELD_MODS],
    tag: "fire",
  },
  {
    id: "shield_04",
    type: "shield",
    name: "Demonvisage Shield",
    description: "La cara de un demonio que escupe fuego por la boca.",
    base: { defense: 55, blockChance: 24, requiredLevel: 18 },
    mods: [...SHIELD_MODS],
    tag: "demonic",
  },
  {
    id: "shield_05",
    type: "shield",
    name: "Icedrake Shield",
    description: "Cabeza de dragón de hielo con cuernos ramificados.",
    base: { defense: 60, blockChance: 25, requiredLevel: 20 },
    mods: [...SHIELD_MODS],
    tag: "cold",
  },
  {
    id: "shield_06",
    type: "shield",
    name: "Crystal Web Ward",
    description: "Telaraña de cristal: no pesa nada y bloquea todo.",
    base: { defense: 34, blockChance: 30, requiredLevel: 10 },
    mods: [...SHIELD_MODS],
    tag: "cold",
  },
  {
    id: "shield_07",
    type: "shield",
    name: "Glacier Bulwark",
    description: "Placas de hielo encimadas como una muralla.",
    base: { defense: 52, blockChance: 22, requiredLevel: 16 },
    mods: [...SHIELD_MODS],
    tag: "cold",
  },
  {
    id: "shield_08",
    type: "shield",
    name: "Stormbolt Shield",
    description: "Un rayo de oro sobre campo azul.",
    base: { defense: 44, blockChance: 20, requiredLevel: 13 },
    mods: [...SHIELD_MODS],
    tag: "lightning",
  },
  {
    id: "shield_09",
    type: "shield",
    name: "Arachnid Bone Shield",
    description: "Hueso y patas de araña gigante. Incómodo de mirar.",
    base: { defense: 42, blockChance: 26, requiredLevel: 15 },
    mods: [...SHIELD_MODS],
    tag: "demonic",
  },
  {
    id: "shield_11",
    type: "shield",
    name: "Voidmaw Shield",
    description: "Una fauce de vacío se abre en el centro del escudo.",
    base: { defense: 58, blockChance: 22, requiredLevel: 19 },
    mods: [...SHIELD_MODS],
    tag: "demonic",
  },
  {
    id: "shield_12",
    type: "shield",
    name: "Seraph's Aegis",
    description: "Rostro alado de serafín labrado en oro macizo.",
    base: { defense: 70, blockChance: 28, requiredLevel: 24 },
    mods: [...SHIELD_MODS],
    tag: "sacred",
  },
  {
    id: "shield_13",
    type: "shield",
    name: "Crusader's Cross Shield",
    description: "Cruz dorada sobre esmalte azul: fe hecha metal.",
    base: { defense: 64, blockChance: 26, requiredLevel: 22 },
    mods: [...SHIELD_MODS],
    tag: "sacred",
  },
  {
    id: "shield_14",
    type: "shield",
    name: "Arcane Sigil Ward",
    description: "Un sello arcano flotante hace de escudo.",
    base: { defense: 36, blockChance: 32, requiredLevel: 12 },
    mods: [...SHIELD_MODS],
    tag: "lightning",
  },

  // =========================================================================
  // ARMADURA (slot armor).
  // =========================================================================
  {
    id: "armor_00",
    type: "armor",
    name: "Runed Wardplate",
    description: "Peto rúnico con placas azules engarzadas en oro.",
    base: { defense: 45, hp: 60, requiredLevel: 8 },
    mods: [...ARMOR_MODS],
    tag: "physical",
  },

  // =========================================================================
  // TOMOS PASIVOS (slots de skill). No tienen `projectile`: no cambian el
  // ataque, sólo suman stats mientras están equipados.
  // =========================================================================
  {
    id: "book_str",
    type: "book_str",
    name: "Tome of Might",
    description: "Tratado de fuerza bruta. Pesa más de lo que parece.",
    effects: ["+40 to life", "+8 to physical damage"],
    base: { hp: 40, damage: 8, requiredLevel: 1 },
    mods: [...TOME_MODS],
    tag: "physical",
  },
  {
    id: "book_int",
    type: "book_int",
    name: "Tome of Insight",
    description: "Notas de un archimago sobre el flujo del maná.",
    effects: ["+35 to mana"],
    base: { requiredLevel: 1 },
    mods: [...TOME_MODS],
    tag: "misc",
  },
  {
    id: "book_dex",
    type: "book_dex",
    name: "Tome of Swiftness",
    description: "Manual de esgrima veloz, ilustrado a mano.",
    effects: ["10% increased attack speed", "+5% critical chance"],
    base: { requiredLevel: 1 },
    // base: { attackSpeed: 10,  requiredLevel: 1 },
    mods: [...TOME_MODS],
    tag: "misc",
  },
];

// ---------------------------------------------------------------------------
// Fábrica de instancias
//
// Los templates de arriba son la definición del item; en los slots (mochila /
// equipo) vive una INSTANCIA con sus mods ya rolleados. Estas funciones viven
// acá (y no en modifiers.js) porque necesitan `item_list`: así la dependencia
// queda en un solo sentido (items.js -> modifiers.js) y no hay ciclo.
// ---------------------------------------------------------------------------

// Copia los campos del template a una instancia concreta (los `mods` ya
// rolleados vienen aparte). Todo lo que el tooltip/el juego necesitan leer de
// un item que está en un slot tiene que copiarse acá.
function instantiate(tpl, mods) {
  return {
    id: tpl.id,
    level: tpl.level,
    baseMods: tpl.baseMods,
    type: tpl.type,
    name: tpl.name,
    tag: tpl.tag,
    base: tpl.base ? { ...tpl.base } : undefined,
    description: tpl.description,
    effects: tpl.effects,
    projectile: tpl.projectile,
    canBeUsedBy: tpl.canBeUsedBy,
    version: tpl.version,
    mods,
  };
}

const findTemplate = (itemId) => item_list.find((it) => it.id === itemId);

// Genera una INSTANCIA de item a partir de su template (item_list): copia sus
// atributos base y le agrega de `minMods` a `maxMods` modificadores tomados al
// azar (sin repetir) de su pool propio (`mods`).
export function rollItem(itemId, { minMods = 0, maxMods = 5 } = {}) {
  const tpl = findTemplate(itemId);
  if (!tpl) return null;
  const pool = tpl.mods || [];
  const count = Math.min(pool.length, modCount(minMods, maxMods));
  const mods = shuffle(pool).slice(0, count).map(rollMod).filter(Boolean);
  // instancia única: estos valores son fijos para este item dropeado
  return instantiate(tpl, mods);
}

// Instancia "base" de un item (sin mods rolleados). Para items iniciales y el
// resultado de crafteo: mismos atributos, 0 modificadores.
export function makeItem(itemId) {
  const tpl = findTemplate(itemId);
  if (!tpl) return null;
  return instantiate(tpl, []);
}
